### ISSUE TITLE
Rag Advanced example 

### ISSUE THREAD

**Issue by ogbozoyan** [ThomasVitale/llm-apps-java-spring-ai#7]
You're implementation of RAG advisor look much better and more professional. Would you like to make a pull request and add it to the Spring AI project ?

And also i didn't quit understand, what's the purpose of those interfaces?
```java
package com.thomasvitale.ai.spring.rag.orchestration.routing.QueryRouter;
```
```java
package com.thomasvitale.ai.spring.rag.postretrieval.document.reranking.DocumentReranker;
```
```java
package com.thomasvitale.ai.spring.rag.postretrieval.document.selection.DocumentSelector;
```
and an empty package 
```
com/thomasvitale/ai/spring/rag/postretrieval/document/compression/
```

**Comment by ogbozoyan** [comment]
@ThomasVitale thanks, Great news, I'll be looking forward

**Comment by ogbozoyan** [comment]
@ThomasVitale, while using your implementation Advanced RAG facing with next problem:
After saving to the vector database my files, which is have information about "Finite field or Galois field", i'm starting to chat with model about cyber security:
---
Input:
query: What is Galois field?
Answer: 
*some answer from model, containing answer from file"
Another input: 
What is man in the middle? 
Answer: 
I can't find information about Man in the Middle in this context. If you would like information about this term, I can suggest you look it up on the Internet or in specialized cybersecurity and computer security sources
---

I think this is because of org.springframework.ai.rag.generation.augmentation.ContextualQueryAugmenter have certain instructions to restrict continue "thinking" model if it's lack of context. How do you manage that situation ?
```java
private static final PromptTemplate DEFAULT_PROMPT_TEMPLATE = new PromptTemplate("""
			Context information is below.

			---------------------
			{context}
			---------------------

			Given the context information and no prior knowledge, answer the query.

			Follow these rules:

			1. If the answer is not in the context, just say that you don't know.
			2. Avoid statements like "Based on the context..." or "The provided information...".

			Query: {query}

			Answer:
			""");
```

MY CONFIGS: 
System prompt:
```
INSTRUCTIONS:
You are a cyber security assistant. You know everything about computer security and information security and are always sharing your knowledge. You need to help and answer questions related to computer, information security. Be ready to explain complex technical terms in simple words. Help users understand the importance of security measures in internet and digital life. Recommend secure practices and tools to protect personal data and devices.
You are friendly and always try to help the person you're talking to, if YOU don't know the answer to a question, gently just answer the user that you're in doubt, but never make up anything
Your role is not only to provide information, but also to motivate people to take care of their digital security. Be helpful and supportive!
```
ChatClient configuration
```kotlin
@Bean
    fun ollamaClient(): ChatClient {
        val documentRetriever: VectorStoreDocumentRetriever = VectorStoreDocumentRetriever.builder()
            .vectorStore(vectorStore)
            .similarityThreshold(0.50)
            .topK(3)
            .build()

        return chatClientBuilder
            .defaultAdvisors(
//                MessageChatMemoryAdvisor(inMemoryChatMemory(), DEFAULT_CHAT_MEMORY_CONVERSATION_ID, 50),
                VectorStoreChatMemoryAdvisor(vectorStore, DEFAULT_CHAT_MEMORY_CONVERSATION_ID, 5),
                SimpleLoggerAdvisor(),
                RetrievalAugmentationAdvisor.builder()
                    .documentRetriever(documentRetriever)
                    .order(Ordered.HIGHEST_PRECEDENCE)
                    .build()
            )
            .build()
    }
    ```
```yaml
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434/}
      embedding:
        options:
          model: ${AI_OLLAMA_EMBEDDING_OPTIONS_MODEL:mxbai-embed-large:latest}
      chat:
        options:
          model: ${OLLAMA_CHAT_MODEL:llama3.2:3b}
          temperature: ${OLLAMA_CHAT_TEMPERATURE:0.6}
          num-ctx: 16384
      vectorstore:
        pgvector:
          initialize-schema: true
          index-type: HNSW
          distance-type: COSINE_DISTANCE
          dimensions: 1024
```
